spring.application.name=SpringProject
server.port = 8025

#MYSQL CONNECTOR INFORMATION
spring.datasource.driver = com.mysql.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/project
spring.datasource.username = root
spring.datasource.password =

#HIBERNET CONFIGURATION
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true